### Importing Necessary Libraries

In [1]:
import pandas as pd
import numpy as np

# featuretools for automated feature engineering
#import featuretools as ft

# matplotlib and seaborn for visualizations
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = 22
import seaborn as sns

# Suppress warnings from pandas
import warnings
warnings.filterwarnings('ignore')

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve, auc, confusion_matrix, classification_report, recall_score, roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

### Merged final file

In [2]:
app_train = pd.read_csv('train_final.csv').sort_values('SK_ID_CURR').reset_index(drop = True)

In [3]:
app_train

Unnamed: 0  SK_ID_CURR  TARGET  NAME_CONTRACT_TYPE  FLAG_OWN_CAR  \
0                0      100002       1                   0             0   
1                1      100003       0                   0             0   
2                2      100004       0                   1             1   
3                3      100006       0                   0             0   
4                4      100007       0                   0             0   
...            ...         ...     ...                 ...           ...   
307506      307506      456251       0                   0             0   
307507      307507      456252       0                   0             0   
307508      307508      456253       0                   0             0   
307509      307509      456254       1                   0             0   
307510      307510      456255       0                   0             0   

        FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  \
0                     1             0          202500.0    406597.5   
1                     0             0          270000.0   1293502.5   
2                     1             0           67500.0    135000.0   
3                     1             0          135000.0    312682.5   
4                     1             0          121500.0    513000.0   
...                 ...           ...               ...         ...   
307506                0             0          157500.0    254700.0   
307507                1             0           72000.0    269550.0   
307508                1             0          153000.0    677664.0   
307509                1             0          171000.0    370107.0   
307510                0             0          157500.0    675000.0   

        AMT_ANNUITY  ...  client_installments_AMT_PAYMENT_min_sum  \
0           24700.5  ...                                175783.73   
1           35698.5  ...                               1154108.20   
2            6750.0  ...                                 16071.75   
3           29686.5  ...                                994476.70   
4           21865.5  ...                                483756.38   
...             ...  ...                                      ...   
307506      27558.0  ...                                 46241.37   
307507      12001.5  ...                                 60281.28   
307508      29979.0  ...                                 41805.99   
307509      20205.0  ...                                194556.81   
307510      49117.5  ...                                171612.27   

        client_installments_AMT_INSTALMENT_min_sum  \
0                                        175783.73   
1                                       1154108.20   
2                                         16071.75   
3                                        994476.70   
4                                        825845.80   
...                                            ...   
307506                                    46241.37   
307507                                    60281.28   
307508                                    61529.04   
307509                                   194556.81   
307510                                  1646200.60   

        client_installments_AMT_PAYMENT_sum_max  \
0                                    219625.700   
1                                   1150977.400   
2                                     21288.465   
3                                    691786.900   
4                                    280199.700   
...                                         ...   
307506                                52450.470   
307507                                60419.203   
307508                                33413.758   
307509                               171592.420   
307510                              2251553.800   

        client_installments_AMT_INSTALMENT_sum_max  \
0                                       219625.700   
1                                      1150

In [4]:
# Dependent variable
x=app_train.drop(columns = ['TARGET','Unnamed: 0'])

In [5]:
x

SK_ID_CURR  NAME_CONTRACT_TYPE  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
0           100002                   0             0                1   
1           100003                   0             0                0   
2           100004                   1             1                1   
3           100006                   0             0                1   
4           100007                   0             0                1   
...            ...                 ...           ...              ...   
307506      456251                   0             0                0   
307507      456252                   0             0                1   
307508      456253                   0             0                1   
307509      456254                   0             0                1   
307510      456255                   0             0                0   

        CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                  0          202500.0    406597.5      24700.5   
1                  0          270000.0   1293502.5      35698.5   
2                  0           67500.0    135000.0       6750.0   
3                  0          135000.0    312682.5      29686.5   
4                  0          121500.0    513000.0      21865.5   
...              ...               ...         ...          ...   
307506             0          157500.0    254700.0      27558.0   
307507             0           72000.0    269550.0      12001.5   
307508             0          153000.0    677664.0      29979.0   
307509             0          171000.0    370107.0      20205.0   
307510             0          157500.0    675000.0      49117.5   

        AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  ...  \
0              351000.0                    0.018801  ...   
1             1129500.0                    0.003541  ...   
2              135000.0                    0.010032  ...   
3              297000.0                    0.008019  ...   
4              513000.0                    0.028663  ...   
...                 ...                         ...  ...   
307506         225000.0                    0.032561  ...   
307507         225000.0                    0.025164  ...   
307508         585000.0                    0.005002  ...   
307509         319500.0                    0.005313  ...   
307510         675000.0                    0.046220  ...   

        client_installments_AMT_PAYMENT_min_sum  \
0                                     175783.73   
1                                    1154108.20   
2                                      16071.75   
3                                     994476.70   
4                                     483756.38   
...                                         ...   
307506                                 46241.37   
307507                                 60281.28   
307508                                 41805.99   
307509                                194556.81   
307510                                171612.27   

        client_installments_AMT_INSTALMENT_min_sum  \
0                                        175783.73   
1                                       1154108.20   
2                                         16071.75   
3                                        994476.70   
4                                        825845.80   
...                                            ...   
307506                                    46241.37   
307507                                    60281.28   
307508                                    61529.04   
307509                                   194556.81   
307510                                  1646200.60   

        client_installments_AMT_PAYMENT_sum_max  \
0                                    219625.700   
1                                   1150977.400   
2                                     21288.465   
3                                    691786.900   
4                                    280199.700   
...                                  

In [6]:
# Independent variable
y=app_train.iloc[:,2].values

In [7]:
y

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [8]:
# Function to find missing values
def missing_values_table(df):
    mis_val=df.isnull().sum()
    mis_val_percent=100*mis_val/len(df)
    mis_val_table=pd.concat([mis_val,mis_val_percent],axis=1)
    mis_val_table_ren_columns=mis_val_table.rename(columns={0:'Missing values',1:'% of Total_values'})
    mis_val_table_ren_columns=mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,1]!=0].sort_values('% of Total_values',ascending=False).round(1)
    return mis_val_table_ren_columns

In [9]:
missing_x=missing_values_table(x)
missing_x

Missing values  % of Total_values
previous_RATE_INTEREST_PRIVILEGED_max          302902               98.5
previous_RATE_INTEREST_PRIMARY_min             302902               98.5
previous_RATE_INTEREST_PRIMARY_mean            302902               98.5
previous_RATE_INTEREST_PRIMARY_max             302902               98.5
previous_RATE_INTEREST_PRIVILEGED_min          302902               98.5
...                                               ...                ...
EXT_SOURCE_2                                      660                0.2
AMT_GOODS_PRICE                                   278                0.1
AMT_ANNUITY                                        12                0.0
CNT_FAM_MEMBERS                                     2                0.0
DAYS_LAST_PHONE_CHANGE                              1                0.0

[1004 rows x 2 columns]

In [10]:
x

SK_ID_CURR  NAME_CONTRACT_TYPE  FLAG_OWN_CAR  FLAG_OWN_REALTY  \
0           100002                   0             0                1   
1           100003                   0             0                0   
2           100004                   1             1                1   
3           100006                   0             0                1   
4           100007                   0             0                1   
...            ...                 ...           ...              ...   
307506      456251                   0             0                0   
307507      456252                   0             0                1   
307508      456253                   0             0                1   
307509      456254                   0             0                1   
307510      456255                   0             0                0   

        CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0                  0          202500.0    406597.5      24700.5   
1                  0          270000.0   1293502.5      35698.5   
2                  0           67500.0    135000.0       6750.0   
3                  0          135000.0    312682.5      29686.5   
4                  0          121500.0    513000.0      21865.5   
...              ...               ...         ...          ...   
307506             0          157500.0    254700.0      27558.0   
307507             0           72000.0    269550.0      12001.5   
307508             0          153000.0    677664.0      29979.0   
307509             0          171000.0    370107.0      20205.0   
307510             0          157500.0    675000.0      49117.5   

        AMT_GOODS_PRICE  REGION_POPULATION_RELATIVE  ...  \
0              351000.0                    0.018801  ...   
1             1129500.0                    0.003541  ...   
2              135000.0                    0.010032  ...   
3              297000.0                    0.008019  ...   
4              513000.0                    0.028663  ...   
...                 ...                         ...  ...   
307506         225000.0                    0.032561  ...   
307507         225000.0                    0.025164  ...   
307508         585000.0                    0.005002  ...   
307509         319500.0                    0.005313  ...   
307510         675000.0                    0.046220  ...   

        client_installments_AMT_PAYMENT_min_sum  \
0                                     175783.73   
1                                    1154108.20   
2                                      16071.75   
3                                     994476.70   
4                                     483756.38   
...                                         ...   
307506                                 46241.37   
307507                                 60281.28   
307508                                 41805.99   
307509                                194556.81   
307510                                171612.27   

        client_installments_AMT_INSTALMENT_min_sum  \
0                                        175783.73   
1                                       1154108.20   
2                                         16071.75   
3                                        994476.70   
4                                        825845.80   
...                                            ...   
307506                                    46241.37   
307507                                    60281.28   
307508                                    61529.04   
307509                                   194556.81   
307510                                  1646200.60   

        client_installments_AMT_PAYMENT_sum_max  \
0                                    219625.700   
1                                   1150977.400   
2                                     21288.465   
3                                    691786.900   
4                                    280199.700   
...                                  

In [11]:
# Imputing missing values
imputer=SimpleImputer(strategy='mean')
imputer.fit(x)
x=imputer.transform(x)

In [12]:
# Converting inf values to zero
x[x<0]=0

In [13]:
# Feature selection
chi2_features = SelectKBest(chi2, k = 1000) 
X_kbest_features = chi2_features.fit_transform(x, y) 

In [14]:
print('Original feature number:', x.shape[1]) 
print('Reduced feature number:', X_kbest_features.shape[1])

Original feature number: 1185
Reduced feature number: 1000


In [15]:
X_kbest_features

array([[1.0000200e+05, 0.0000000e+00, 0.0000000e+00, ..., 1.0087812e+06,
        4.1728882e+06, 4.1728882e+06],
       [1.0000300e+05, 0.0000000e+00, 0.0000000e+00, ..., 4.3941015e+06,
        1.1348806e+07, 1.1348806e+07],
       [1.0000400e+05, 1.0000000e+00, 1.0000000e+00, ..., 3.1721895e+04,
        6.3865395e+04, 6.3865395e+04],
       ...,
       [4.5625300e+05, 0.0000000e+00, 0.0000000e+00, ..., 6.1661746e+04,
        3.0489203e+05, 3.2475750e+05],
       [4.5625400e+05, 0.0000000e+00, 0.0000000e+00, ..., 1.9455681e+05,
        1.7739758e+06, 1.7739758e+06],
       [4.5625500e+05, 0.0000000e+00, 0.0000000e+00, ..., 2.5724196e+07,
        8.1350776e+07, 6.6436548e+07]])

### Logistic Regression

In [16]:
x_train,x_test,y_train,y_test=train_test_split(X_kbest_features,y,test_size=0.3,random_state=0)

In [17]:
classifier=LogisticRegression(C=0.1)
classifier.fit(x_train,y_train)

LogisticRegression(C=0.1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [18]:
y_pred=classifier.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[84870    44]
 [ 7327    13]]


0.9201010254297917

In [20]:
roc_auc_score(y_test, y_pred)

0.5006264729199646